In [2]:
import numpy as np
ar1 = np.arange(16)
ar2 = np.zeros((2,8))
print(ar1)
print(ar2)
print(ar1.T) # 矩阵的转置
print(ar2.T)
print(ar1.reshape(4,4))
print(np.ones((2,5)).reshape(5,2))

print(np.resize(np.arange(5),(3,4)))
print(np.reshape(np.arange(16),(2,8)))# 保证数一样

print(np.resize(np.arange(5),(3,4))) # 循环填满 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


In [4]:
ar3 = np.arange(10)
ar4 = ar3
print(ar3 is ar4)
ar4 = ar3.copy()


True


In [8]:
ar1 = np.arange(10,dtype=float)
ar2 = ar1.astype(np.int)
print(ar1.dtype)
print(ar2.dtype)

float64
int32


In [19]:
a = np.arange(4)
b = np.arange(5,9)
print(a)
print(b)
print(np.hstack((a,b))) #横向连接
print(a.reshape(a.shape[0],1))
print(np.vstack((a,b))) #纵向连接

print(np.stack((a,b),axis=0)) #连接 ，使用参数
print(np.stack((a,b),axis=1)) #连接 ，使用参数


[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]
 [5 6 7 8]]
[[0 1 2 3]
 [5 6 7 8]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]]


In [21]:
#数组的拆分
ar = np.arange(16).reshape(4,4)
print(ar)
print(np.hsplit(ar,2)[0])
print(np.vsplit(ar,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
